{
 "title": "PSY Traveler Events Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Airport Events",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT count( AIRPORT ) as `counter`,  AIRPORT  FROM USER_EVENTS_AVRO WINDOW TUMBLING (SIZE 10800 SECONDS) GROUP BY AIRPORT EMIT CHANGES;"
    }
   ]
  },
  {
   "title": "Traveler Statuses",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "queryText": " SELECT STATUS as `TravelerStatus`, COUNT(STATUS) as `Total`, AIRPORT FROM BY_STATUSES WINDOW TUMBLING (SIZE 10800 SECONDS) GROUP BY STATUS, AIRPORT EMIT CHANGES; "
    }
   ]
  },
  {
   "title": "All Airport Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "select ROWTIME_FORMATTED as `EVENT TIME`, STATUS, FIRST_NAME, LAST_NAME, GENDER, AGE, EYECOLOR, EMAIL, PHONE_NUMBER, STREET_ADDRESS, STATE,ZIP_CODE,COUNTRY from user_events_avro;"
    }
   ]
  }
 ]
}