---
version: '2'
services:
#  postgres_db:
#    image: postgres:13.0
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: example
#
#  grafana:
#    image: grafana/grafana
#    depends_on:
#      - postgres_db
#    ports:
#      - 3000:3000
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
#    environment:
#      GF_INSTALL_PLUGINS: grafana-worldmap-panel
#      GF_AUTH_DISABLE_LOGIN_FORM: "true"
#      GF_AUTH_ANONYMOUS_ENABLED: "true"
#      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

  jms-bridge:
    hostname: JMS_BRIDGE
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
        - 61616:61616
    environment:
      - JMSBRIDGE_ID=JMS_BRIDGE

      - JMSBRIDGE_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - JMSBRIDGE_SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}

      - JMSBRIDGE_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - JMSBRIDGE_KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - JMSBRIDGE_KAFKA_SASL_MECHANISM=PLAIN
      - JMSBRIDGE_KAFKA_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';
      - JMSBRIDGE_JOURNALS_TOPIC_REPLICATION=3

      - JMSBRIDGE_KAFKA_SCHEMA_REGISTRY_API_ID=${SCHEMA_REGISTRY_API_ID}
      - JMSBRIDGE_KAFKA_SCHEMA_REGISTRY_API_SECRET=${SCHEMA_REGISTRY_API_SECRET}
      - JMSBRIDGE_KAFKA_BASIC_AUTH_CREDENTIALS=USER_INFO
      
      - JMSBRIDGE_ROUTING_TOPICS_0_MATCH=^psy-travel.*
      - JMSBRIDGE_ROUTING_TOPICS_0_MESSAGE_TYPE=TEXT
